version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - unused

  disable:
    - errcheck

  settings:
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-specific: false
    staticcheck:
      checks:
        - all
        - -QF1003
        - -ST1000
        - -ST1020

formatters:
  enable:
    - gofmt
    - goimports
