version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/omen
    binary: omen
    env:
      - CGO_ENABLED=1
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
    ignore:
      - goos: linux
        goarch: amd64
        if: '{{ ne .Runtime.Goos "linux" }}'
      - goos: linux
        goarch: arm64
        if: '{{ ne .Runtime.Goos "linux" }}'
      - goos: darwin
        goarch: amd64
        if: '{{ ne .Runtime.Goos "darwin" }}'
      - goos: darwin
        goarch: arm64
        if: '{{ ne .Runtime.Goos "darwin" }}'
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - omen.example.toml

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

release:
  github:
    owner: panbanda
    name: omen
  mode: append
