version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    main: ./cmd/omen
    binary: omen
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    skip: '{{ and (isEnvSet "GOOS") (or (ne .Env.GOOS "linux") (ne .Env.GOARCH "amd64")) }}'
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}
  - id: linux-arm64
    main: ./cmd/omen
    binary: omen
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - arm64
    skip: '{{ and (isEnvSet "GOOS") (or (ne .Env.GOOS "linux") (ne .Env.GOARCH "arm64")) }}'
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}
  - id: darwin-amd64
    main: ./cmd/omen
    binary: omen
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    skip: '{{ and (isEnvSet "GOOS") (or (ne .Env.GOOS "darwin") (ne .Env.GOARCH "amd64")) }}'
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}
  - id: darwin-arm64
    main: ./cmd/omen
    binary: omen
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    skip: '{{ and (isEnvSet "GOOS") (or (ne .Env.GOOS "darwin") (ne .Env.GOARCH "arm64")) }}'
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - omen.example.toml

checksum:
  name_template: "checksums_{{ .Env.GOOS }}_{{ .Env.GOARCH }}.txt"

changelog:
  disable: true

release:
  github:
    owner: panbanda
    name: omen
  mode: append
