version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    main: ./cmd/omen
    binary: omen
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    skip: '{{ and (isEnvSet "GOOS") (or (ne .Env.GOOS "linux") (ne .Env.GOARCH "amd64")) }}'
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}
  - id: linux-arm64
    main: ./cmd/omen
    binary: omen
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - arm64
    skip: '{{ and (isEnvSet "GOOS") (or (ne .Env.GOOS "linux") (ne .Env.GOARCH "arm64")) }}'
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}
  - id: darwin-amd64
    main: ./cmd/omen
    binary: omen
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    skip: '{{ and (isEnvSet "GOOS") (or (ne .Env.GOOS "darwin") (ne .Env.GOARCH "amd64")) }}'
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}
  - id: darwin-arm64
    main: ./cmd/omen
    binary: omen
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    skip: '{{ and (isEnvSet "GOOS") (or (ne .Env.GOOS "darwin") (ne .Env.GOARCH "arm64")) }}'
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - omen.example.toml

checksum:
  name_template: "checksums_{{ .Env.GOOS }}_{{ .Env.GOARCH }}.txt"

changelog:
  disable: true

release:
  github:
    owner: panbanda
    name: omen
  mode: append

brews:
  - name: omen
    repository:
      owner: panbanda
      name: homebrew-omen
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/panbanda/omen"
    description: "Multi-language code analysis CLI"
    license: "MIT"
    test: |
      system "#{bin}/omen", "--version"

dockers:
  - id: linux-amd64
    ids:
      - linux-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/panbanda/omen:{{ trimprefix .Version \"omen-v\" }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ trimprefix .Version \"omen-v\" }}"
      - "--label=org.opencontainers.image.source=https://github.com/panbanda/omen"
      - "--platform=linux/amd64"
  - id: linux-arm64
    ids:
      - linux-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/panbanda/omen:{{ trimprefix .Version \"omen-v\" }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ trimprefix .Version \"omen-v\" }}"
      - "--label=org.opencontainers.image.source=https://github.com/panbanda/omen"
      - "--platform=linux/arm64"

mcp:
  github:
    name: io.github.panbanda/omen
    title: Omen
    description: Multi-language code analysis tools for complexity, technical debt, hotspots, ownership, and defect prediction
    homepage: https://github.com/panbanda/omen
    repository:
      url: https://github.com/panbanda/omen
      source: github
      id: panbanda/omen
    auth:
      type: github-oidc
    packages:
      - identifier: ghcr.io/panbanda/omen
        registry_type: oci
        transport:
          type: stdio
    transports:
      - type: stdio
