with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
packages:
  github.com/panbanda/omen/internal/vcs:
    interfaces:
      Repository:
      Reference:
      CommitIterator:
      Commit:
      Tree:
      Change:
      Patch:
      FilePatch:
      Chunk:
      Opener:
