dir: '{{.InterfaceDir}}/mocks'
filename: mock_{{.InterfaceName | snakecase}}.go
structname: Mock{{.InterfaceName}}
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/panbanda/omen/internal/vcs:
    interfaces:
      Change: {}
      Chunk: {}
      Commit: {}
      CommitIterator: {}
      FilePatch: {}
      Opener: {}
      Patch: {}
      Reference: {}
      Repository: {}
      Tree: {}
