version: '3'

tasks:
  tidy:
    desc: Format code and tidy dependencies
    cmds:
      - go fmt ./...
      - go mod tidy
      - go vet ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  test:
    desc: Run all checks and tests
    cmds:
      - task: lint
      - go test -race ./...
