version: '3'

tasks:
  setup:
    desc: Install git hooks via lefthook
    cmds:
      - lefthook install

  build:
    desc: Build the omen CLI
    cmds:
      - go build -o omen ./cmd/omen

  tidy:
    desc: Format code and tidy dependencies
    cmds:
      - go fmt ./...
      - go mod tidy
      - go vet ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  test:
    desc: Run all checks and tests
    cmds:
      - task: lint
      - go test ./...

  test-race:
    desc: Run tests with race detector (slower, for CI)
    cmds:
      - task: lint
      - go test -race ./...
