// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/go-git/go-git/v5/plumbing"
	"github.com/panbanda/omen/internal/vcs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Blame provides a mock function for the type MockRepository
func (_mock *MockRepository) Blame(commit vcs.Commit, path string) (*vcs.BlameResult, error) {
	ret := _mock.Called(commit, path)

	if len(ret) == 0 {
		panic("no return value specified for Blame")
	}

	var r0 *vcs.BlameResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(vcs.Commit, string) (*vcs.BlameResult, error)); ok {
		return returnFunc(commit, path)
	}
	if returnFunc, ok := ret.Get(0).(func(vcs.Commit, string) *vcs.BlameResult); ok {
		r0 = returnFunc(commit, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vcs.BlameResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(vcs.Commit, string) error); ok {
		r1 = returnFunc(commit, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Blame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Blame'
type MockRepository_Blame_Call struct {
	*mock.Call
}

// Blame is a helper method to define mock.On call
//   - commit vcs.Commit
//   - path string
func (_e *MockRepository_Expecter) Blame(commit interface{}, path interface{}) *MockRepository_Blame_Call {
	return &MockRepository_Blame_Call{Call: _e.mock.On("Blame", commit, path)}
}

func (_c *MockRepository_Blame_Call) Run(run func(commit vcs.Commit, path string)) *MockRepository_Blame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 vcs.Commit
		if args[0] != nil {
			arg0 = args[0].(vcs.Commit)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Blame_Call) Return(blameResult *vcs.BlameResult, err error) *MockRepository_Blame_Call {
	_c.Call.Return(blameResult, err)
	return _c
}

func (_c *MockRepository_Blame_Call) RunAndReturn(run func(commit vcs.Commit, path string) (*vcs.BlameResult, error)) *MockRepository_Blame_Call {
	_c.Call.Return(run)
	return _c
}

// CommitObject provides a mock function for the type MockRepository
func (_mock *MockRepository) CommitObject(hash plumbing.Hash) (vcs.Commit, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for CommitObject")
	}

	var r0 vcs.Commit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(plumbing.Hash) (vcs.Commit, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(plumbing.Hash) vcs.Commit); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.Commit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(plumbing.Hash) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CommitObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitObject'
type MockRepository_CommitObject_Call struct {
	*mock.Call
}

// CommitObject is a helper method to define mock.On call
//   - hash plumbing.Hash
func (_e *MockRepository_Expecter) CommitObject(hash interface{}) *MockRepository_CommitObject_Call {
	return &MockRepository_CommitObject_Call{Call: _e.mock.On("CommitObject", hash)}
}

func (_c *MockRepository_CommitObject_Call) Run(run func(hash plumbing.Hash)) *MockRepository_CommitObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 plumbing.Hash
		if args[0] != nil {
			arg0 = args[0].(plumbing.Hash)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_CommitObject_Call) Return(commit vcs.Commit, err error) *MockRepository_CommitObject_Call {
	_c.Call.Return(commit, err)
	return _c
}

func (_c *MockRepository_CommitObject_Call) RunAndReturn(run func(hash plumbing.Hash) (vcs.Commit, error)) *MockRepository_CommitObject_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function for the type MockRepository
func (_mock *MockRepository) Head() (vcs.Reference, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 vcs.Reference
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (vcs.Reference, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() vcs.Reference); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.Reference)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockRepository_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Head() *MockRepository_Head_Call {
	return &MockRepository_Head_Call{Call: _e.mock.On("Head")}
}

func (_c *MockRepository_Head_Call) Run(run func()) *MockRepository_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Head_Call) Return(reference vcs.Reference, err error) *MockRepository_Head_Call {
	_c.Call.Return(reference, err)
	return _c
}

func (_c *MockRepository_Head_Call) RunAndReturn(run func() (vcs.Reference, error)) *MockRepository_Head_Call {
	_c.Call.Return(run)
	return _c
}

// Log provides a mock function for the type MockRepository
func (_mock *MockRepository) Log(opts *vcs.LogOptions) (vcs.CommitIterator, error) {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 vcs.CommitIterator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*vcs.LogOptions) (vcs.CommitIterator, error)); ok {
		return returnFunc(opts)
	}
	if returnFunc, ok := ret.Get(0).(func(*vcs.LogOptions) vcs.CommitIterator); ok {
		r0 = returnFunc(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.CommitIterator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*vcs.LogOptions) error); ok {
		r1 = returnFunc(opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockRepository_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - opts *vcs.LogOptions
func (_e *MockRepository_Expecter) Log(opts interface{}) *MockRepository_Log_Call {
	return &MockRepository_Log_Call{Call: _e.mock.On("Log", opts)}
}

func (_c *MockRepository_Log_Call) Run(run func(opts *vcs.LogOptions)) *MockRepository_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *vcs.LogOptions
		if args[0] != nil {
			arg0 = args[0].(*vcs.LogOptions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Log_Call) Return(commitIterator vcs.CommitIterator, err error) *MockRepository_Log_Call {
	_c.Call.Return(commitIterator, err)
	return _c
}

func (_c *MockRepository_Log_Call) RunAndReturn(run func(opts *vcs.LogOptions) (vcs.CommitIterator, error)) *MockRepository_Log_Call {
	_c.Call.Return(run)
	return _c
}

// BlameAtHead provides a mock function for the type MockRepository
func (_mock *MockRepository) BlameAtHead(path string) (*vcs.BlameResult, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for BlameAtHead")
	}

	var r0 *vcs.BlameResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*vcs.BlameResult, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *vcs.BlameResult); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vcs.BlameResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_BlameAtHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlameAtHead'
type MockRepository_BlameAtHead_Call struct {
	*mock.Call
}

// BlameAtHead is a helper method to define mock.On call
//   - path string
func (_e *MockRepository_Expecter) BlameAtHead(path interface{}) *MockRepository_BlameAtHead_Call {
	return &MockRepository_BlameAtHead_Call{Call: _e.mock.On("BlameAtHead", path)}
}

func (_c *MockRepository_BlameAtHead_Call) Run(run func(path string)) *MockRepository_BlameAtHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(arg0)
	})
	return _c
}

func (_c *MockRepository_BlameAtHead_Call) Return(blameResult *vcs.BlameResult, err error) *MockRepository_BlameAtHead_Call {
	_c.Call.Return(blameResult, err)
	return _c
}

func (_c *MockRepository_BlameAtHead_Call) RunAndReturn(run func(path string) (*vcs.BlameResult, error)) *MockRepository_BlameAtHead_Call {
	_c.Call.Return(run)
	return _c
}

// RepoPath provides a mock function for the type MockRepository
func (_mock *MockRepository) RepoPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RepoPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRepository_RepoPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepoPath'
type MockRepository_RepoPath_Call struct {
	*mock.Call
}

// RepoPath is a helper method to define mock.On call
func (_e *MockRepository_Expecter) RepoPath() *MockRepository_RepoPath_Call {
	return &MockRepository_RepoPath_Call{Call: _e.mock.On("RepoPath")}
}

func (_c *MockRepository_RepoPath_Call) Run(run func()) *MockRepository_RepoPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_RepoPath_Call) Return(path string) *MockRepository_RepoPath_Call {
	_c.Call.Return(path)
	return _c
}

func (_c *MockRepository_RepoPath_Call) RunAndReturn(run func() string) *MockRepository_RepoPath_Call {
	_c.Call.Return(run)
	return _c
}
