// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	vcs "github.com/panbanda/omen/internal/vcs"
	mock "github.com/stretchr/testify/mock"
)

// MockChange is an autogenerated mock type for the Change type
type MockChange struct {
	mock.Mock
}

type MockChange_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChange) EXPECT() *MockChange_Expecter {
	return &MockChange_Expecter{mock: &_m.Mock}
}

// FromName provides a mock function with no fields
func (_m *MockChange) FromName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FromName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockChange_FromName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromName'
type MockChange_FromName_Call struct {
	*mock.Call
}

// FromName is a helper method to define mock.On call
func (_e *MockChange_Expecter) FromName() *MockChange_FromName_Call {
	return &MockChange_FromName_Call{Call: _e.mock.On("FromName")}
}

func (_c *MockChange_FromName_Call) Run(run func()) *MockChange_FromName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChange_FromName_Call) Return(_a0 string) *MockChange_FromName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChange_FromName_Call) RunAndReturn(run func() string) *MockChange_FromName_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with no fields
func (_m *MockChange) Patch() (vcs.Patch, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 vcs.Patch
	var r1 error
	if rf, ok := ret.Get(0).(func() (vcs.Patch, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() vcs.Patch); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.Patch)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChange_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockChange_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
func (_e *MockChange_Expecter) Patch() *MockChange_Patch_Call {
	return &MockChange_Patch_Call{Call: _e.mock.On("Patch")}
}

func (_c *MockChange_Patch_Call) Run(run func()) *MockChange_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChange_Patch_Call) Return(_a0 vcs.Patch, _a1 error) *MockChange_Patch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChange_Patch_Call) RunAndReturn(run func() (vcs.Patch, error)) *MockChange_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// ToName provides a mock function with no fields
func (_m *MockChange) ToName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockChange_ToName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToName'
type MockChange_ToName_Call struct {
	*mock.Call
}

// ToName is a helper method to define mock.On call
func (_e *MockChange_Expecter) ToName() *MockChange_ToName_Call {
	return &MockChange_ToName_Call{Call: _e.mock.On("ToName")}
}

func (_c *MockChange_ToName_Call) Run(run func()) *MockChange_ToName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChange_ToName_Call) Return(_a0 string) *MockChange_ToName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChange_ToName_Call) RunAndReturn(run func() string) *MockChange_ToName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChange creates a new instance of MockChange. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChange(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChange {
	mock := &MockChange{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
