// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/panbanda/omen/internal/vcs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChunk creates a new instance of MockChunk. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunk(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunk {
	mock := &MockChunk{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChunk is an autogenerated mock type for the Chunk type
type MockChunk struct {
	mock.Mock
}

type MockChunk_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChunk) EXPECT() *MockChunk_Expecter {
	return &MockChunk_Expecter{mock: &_m.Mock}
}

// Content provides a mock function for the type MockChunk
func (_mock *MockChunk) Content() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Content")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockChunk_Content_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Content'
type MockChunk_Content_Call struct {
	*mock.Call
}

// Content is a helper method to define mock.On call
func (_e *MockChunk_Expecter) Content() *MockChunk_Content_Call {
	return &MockChunk_Content_Call{Call: _e.mock.On("Content")}
}

func (_c *MockChunk_Content_Call) Run(run func()) *MockChunk_Content_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChunk_Content_Call) Return(s string) *MockChunk_Content_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockChunk_Content_Call) RunAndReturn(run func() string) *MockChunk_Content_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockChunk
func (_mock *MockChunk) Type() vcs.ChunkType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 vcs.ChunkType
	if returnFunc, ok := ret.Get(0).(func() vcs.ChunkType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(vcs.ChunkType)
	}
	return r0
}

// MockChunk_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockChunk_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockChunk_Expecter) Type() *MockChunk_Type_Call {
	return &MockChunk_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockChunk_Type_Call) Run(run func()) *MockChunk_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChunk_Type_Call) Return(chunkType vcs.ChunkType) *MockChunk_Type_Call {
	_c.Call.Return(chunkType)
	return _c
}

func (_c *MockChunk_Type_Call) RunAndReturn(run func() vcs.ChunkType) *MockChunk_Type_Call {
	_c.Call.Return(run)
	return _c
}
