// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/go-git/go-git/v5/plumbing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReference creates a new instance of MockReference. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReference(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReference {
	mock := &MockReference{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReference is an autogenerated mock type for the Reference type
type MockReference struct {
	mock.Mock
}

type MockReference_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReference) EXPECT() *MockReference_Expecter {
	return &MockReference_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type MockReference
func (_mock *MockReference) Hash() plumbing.Hash {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 plumbing.Hash
	if returnFunc, ok := ret.Get(0).(func() plumbing.Hash); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}
	return r0
}

// MockReference_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockReference_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
func (_e *MockReference_Expecter) Hash() *MockReference_Hash_Call {
	return &MockReference_Hash_Call{Call: _e.mock.On("Hash")}
}

func (_c *MockReference_Hash_Call) Run(run func()) *MockReference_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReference_Hash_Call) Return(hash plumbing.Hash) *MockReference_Hash_Call {
	_c.Call.Return(hash)
	return _c
}

func (_c *MockReference_Hash_Call) RunAndReturn(run func() plumbing.Hash) *MockReference_Hash_Call {
	_c.Call.Return(run)
	return _c
}
