// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/panbanda/omen/internal/vcs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTree creates a new instance of MockTree. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTree(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTree {
	mock := &MockTree{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTree is an autogenerated mock type for the Tree type
type MockTree struct {
	mock.Mock
}

type MockTree_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTree) EXPECT() *MockTree_Expecter {
	return &MockTree_Expecter{mock: &_m.Mock}
}

// Diff provides a mock function for the type MockTree
func (_mock *MockTree) Diff(to vcs.Tree) (vcs.Changes, error) {
	ret := _mock.Called(to)

	if len(ret) == 0 {
		panic("no return value specified for Diff")
	}

	var r0 vcs.Changes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(vcs.Tree) (vcs.Changes, error)); ok {
		return returnFunc(to)
	}
	if returnFunc, ok := ret.Get(0).(func(vcs.Tree) vcs.Changes); ok {
		r0 = returnFunc(to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.Changes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(vcs.Tree) error); ok {
		r1 = returnFunc(to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTree_Diff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Diff'
type MockTree_Diff_Call struct {
	*mock.Call
}

// Diff is a helper method to define mock.On call
//   - to vcs.Tree
func (_e *MockTree_Expecter) Diff(to interface{}) *MockTree_Diff_Call {
	return &MockTree_Diff_Call{Call: _e.mock.On("Diff", to)}
}

func (_c *MockTree_Diff_Call) Run(run func(to vcs.Tree)) *MockTree_Diff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 vcs.Tree
		if args[0] != nil {
			arg0 = args[0].(vcs.Tree)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTree_Diff_Call) Return(changes vcs.Changes, err error) *MockTree_Diff_Call {
	_c.Call.Return(changes, err)
	return _c
}

func (_c *MockTree_Diff_Call) RunAndReturn(run func(to vcs.Tree) (vcs.Changes, error)) *MockTree_Diff_Call {
	_c.Call.Return(run)
	return _c
}

// Entries provides a mock function for the type MockTree
func (_mock *MockTree) Entries() ([]vcs.TreeEntry, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Entries")
	}

	var r0 []vcs.TreeEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]vcs.TreeEntry, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []vcs.TreeEntry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vcs.TreeEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTree_Entries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Entries'
type MockTree_Entries_Call struct {
	*mock.Call
}

// Entries is a helper method to define mock.On call
func (_e *MockTree_Expecter) Entries() *MockTree_Entries_Call {
	return &MockTree_Entries_Call{Call: _e.mock.On("Entries")}
}

func (_c *MockTree_Entries_Call) Run(run func()) *MockTree_Entries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTree_Entries_Call) Return(entries []vcs.TreeEntry, err error) *MockTree_Entries_Call {
	_c.Call.Return(entries, err)
	return _c
}

func (_c *MockTree_Entries_Call) RunAndReturn(run func() ([]vcs.TreeEntry, error)) *MockTree_Entries_Call {
	_c.Call.Return(run)
	return _c
}
