// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/go-git/go-git/v5/plumbing"
	"github.com/go-git/go-git/v5/plumbing/object"
	"github.com/panbanda/omen/internal/vcs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommit creates a new instance of MockCommit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommit {
	mock := &MockCommit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommit is an autogenerated mock type for the Commit type
type MockCommit struct {
	mock.Mock
}

type MockCommit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommit) EXPECT() *MockCommit_Expecter {
	return &MockCommit_Expecter{mock: &_m.Mock}
}

// Author provides a mock function for the type MockCommit
func (_mock *MockCommit) Author() object.Signature {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Author")
	}

	var r0 object.Signature
	if returnFunc, ok := ret.Get(0).(func() object.Signature); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(object.Signature)
	}
	return r0
}

// MockCommit_Author_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Author'
type MockCommit_Author_Call struct {
	*mock.Call
}

// Author is a helper method to define mock.On call
func (_e *MockCommit_Expecter) Author() *MockCommit_Author_Call {
	return &MockCommit_Author_Call{Call: _e.mock.On("Author")}
}

func (_c *MockCommit_Author_Call) Run(run func()) *MockCommit_Author_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommit_Author_Call) Return(signature object.Signature) *MockCommit_Author_Call {
	_c.Call.Return(signature)
	return _c
}

func (_c *MockCommit_Author_Call) RunAndReturn(run func() object.Signature) *MockCommit_Author_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockCommit
func (_mock *MockCommit) Hash() plumbing.Hash {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 plumbing.Hash
	if returnFunc, ok := ret.Get(0).(func() plumbing.Hash); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}
	return r0
}

// MockCommit_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockCommit_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
func (_e *MockCommit_Expecter) Hash() *MockCommit_Hash_Call {
	return &MockCommit_Hash_Call{Call: _e.mock.On("Hash")}
}

func (_c *MockCommit_Hash_Call) Run(run func()) *MockCommit_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommit_Hash_Call) Return(hash plumbing.Hash) *MockCommit_Hash_Call {
	_c.Call.Return(hash)
	return _c
}

func (_c *MockCommit_Hash_Call) RunAndReturn(run func() plumbing.Hash) *MockCommit_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NumParents provides a mock function for the type MockCommit
func (_mock *MockCommit) NumParents() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NumParents")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockCommit_NumParents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NumParents'
type MockCommit_NumParents_Call struct {
	*mock.Call
}

// NumParents is a helper method to define mock.On call
func (_e *MockCommit_Expecter) NumParents() *MockCommit_NumParents_Call {
	return &MockCommit_NumParents_Call{Call: _e.mock.On("NumParents")}
}

func (_c *MockCommit_NumParents_Call) Run(run func()) *MockCommit_NumParents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommit_NumParents_Call) Return(n int) *MockCommit_NumParents_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCommit_NumParents_Call) RunAndReturn(run func() int) *MockCommit_NumParents_Call {
	_c.Call.Return(run)
	return _c
}

// Parent provides a mock function for the type MockCommit
func (_mock *MockCommit) Parent(n int) (vcs.Commit, error) {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Parent")
	}

	var r0 vcs.Commit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (vcs.Commit, error)); ok {
		return returnFunc(n)
	}
	if returnFunc, ok := ret.Get(0).(func(int) vcs.Commit); ok {
		r0 = returnFunc(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.Commit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommit_Parent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parent'
type MockCommit_Parent_Call struct {
	*mock.Call
}

// Parent is a helper method to define mock.On call
//   - n int
func (_e *MockCommit_Expecter) Parent(n interface{}) *MockCommit_Parent_Call {
	return &MockCommit_Parent_Call{Call: _e.mock.On("Parent", n)}
}

func (_c *MockCommit_Parent_Call) Run(run func(n int)) *MockCommit_Parent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommit_Parent_Call) Return(commit vcs.Commit, err error) *MockCommit_Parent_Call {
	_c.Call.Return(commit, err)
	return _c
}

func (_c *MockCommit_Parent_Call) RunAndReturn(run func(n int) (vcs.Commit, error)) *MockCommit_Parent_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockCommit
func (_mock *MockCommit) Stats() (object.FileStats, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 object.FileStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (object.FileStats, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() object.FileStats); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(object.FileStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommit_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockCommit_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockCommit_Expecter) Stats() *MockCommit_Stats_Call {
	return &MockCommit_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockCommit_Stats_Call) Run(run func()) *MockCommit_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommit_Stats_Call) Return(fileStats object.FileStats, err error) *MockCommit_Stats_Call {
	_c.Call.Return(fileStats, err)
	return _c
}

func (_c *MockCommit_Stats_Call) RunAndReturn(run func() (object.FileStats, error)) *MockCommit_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// Tree provides a mock function for the type MockCommit
func (_mock *MockCommit) Tree() (vcs.Tree, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tree")
	}

	var r0 vcs.Tree
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (vcs.Tree, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() vcs.Tree); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.Tree)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommit_Tree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tree'
type MockCommit_Tree_Call struct {
	*mock.Call
}

// Tree is a helper method to define mock.On call
func (_e *MockCommit_Expecter) Tree() *MockCommit_Tree_Call {
	return &MockCommit_Tree_Call{Call: _e.mock.On("Tree")}
}

func (_c *MockCommit_Tree_Call) Run(run func()) *MockCommit_Tree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommit_Tree_Call) Return(tree vcs.Tree, err error) *MockCommit_Tree_Call {
	_c.Call.Return(tree, err)
	return _c
}

func (_c *MockCommit_Tree_Call) RunAndReturn(run func() (vcs.Tree, error)) *MockCommit_Tree_Call {
	_c.Call.Return(run)
	return _c
}
