// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	vcs "github.com/panbanda/omen/internal/vcs"
	mock "github.com/stretchr/testify/mock"
)

// MockOpener is an autogenerated mock type for the Opener type
type MockOpener struct {
	mock.Mock
}

type MockOpener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpener) EXPECT() *MockOpener_Expecter {
	return &MockOpener_Expecter{mock: &_m.Mock}
}

// PlainOpen provides a mock function with given fields: path
func (_m *MockOpener) PlainOpen(path string) (vcs.Repository, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for PlainOpen")
	}

	var r0 vcs.Repository
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (vcs.Repository, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) vcs.Repository); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOpener_PlainOpen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlainOpen'
type MockOpener_PlainOpen_Call struct {
	*mock.Call
}

// PlainOpen is a helper method to define mock.On call
//   - path string
func (_e *MockOpener_Expecter) PlainOpen(path interface{}) *MockOpener_PlainOpen_Call {
	return &MockOpener_PlainOpen_Call{Call: _e.mock.On("PlainOpen", path)}
}

func (_c *MockOpener_PlainOpen_Call) Run(run func(path string)) *MockOpener_PlainOpen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOpener_PlainOpen_Call) Return(_a0 vcs.Repository, _a1 error) *MockOpener_PlainOpen_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOpener_PlainOpen_Call) RunAndReturn(run func(string) (vcs.Repository, error)) *MockOpener_PlainOpen_Call {
	_c.Call.Return(run)
	return _c
}

// PlainOpenWithDetect provides a mock function with given fields: path
func (_m *MockOpener) PlainOpenWithDetect(path string) (vcs.Repository, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for PlainOpenWithDetect")
	}

	var r0 vcs.Repository
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (vcs.Repository, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) vcs.Repository); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOpener_PlainOpenWithDetect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlainOpenWithDetect'
type MockOpener_PlainOpenWithDetect_Call struct {
	*mock.Call
}

// PlainOpenWithDetect is a helper method to define mock.On call
//   - path string
func (_e *MockOpener_Expecter) PlainOpenWithDetect(path interface{}) *MockOpener_PlainOpenWithDetect_Call {
	return &MockOpener_PlainOpenWithDetect_Call{Call: _e.mock.On("PlainOpenWithDetect", path)}
}

func (_c *MockOpener_PlainOpenWithDetect_Call) Run(run func(path string)) *MockOpener_PlainOpenWithDetect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOpener_PlainOpenWithDetect_Call) Return(_a0 vcs.Repository, _a1 error) *MockOpener_PlainOpenWithDetect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOpener_PlainOpenWithDetect_Call) RunAndReturn(run func(string) (vcs.Repository, error)) *MockOpener_PlainOpenWithDetect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOpener creates a new instance of MockOpener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpener {
	mock := &MockOpener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
