// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	plumbing "github.com/go-git/go-git/v5/plumbing"
	mock "github.com/stretchr/testify/mock"

	vcs "github.com/panbanda/omen/internal/vcs"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Blame provides a mock function with given fields: commit, path
func (_m *MockRepository) Blame(commit vcs.Commit, path string) (*vcs.BlameResult, error) {
	ret := _m.Called(commit, path)

	if len(ret) == 0 {
		panic("no return value specified for Blame")
	}

	var r0 *vcs.BlameResult
	var r1 error
	if rf, ok := ret.Get(0).(func(vcs.Commit, string) (*vcs.BlameResult, error)); ok {
		return rf(commit, path)
	}
	if rf, ok := ret.Get(0).(func(vcs.Commit, string) *vcs.BlameResult); ok {
		r0 = rf(commit, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vcs.BlameResult)
		}
	}

	if rf, ok := ret.Get(1).(func(vcs.Commit, string) error); ok {
		r1 = rf(commit, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Blame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Blame'
type MockRepository_Blame_Call struct {
	*mock.Call
}

// Blame is a helper method to define mock.On call
//   - commit vcs.Commit
//   - path string
func (_e *MockRepository_Expecter) Blame(commit interface{}, path interface{}) *MockRepository_Blame_Call {
	return &MockRepository_Blame_Call{Call: _e.mock.On("Blame", commit, path)}
}

func (_c *MockRepository_Blame_Call) Run(run func(commit vcs.Commit, path string)) *MockRepository_Blame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(vcs.Commit), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_Blame_Call) Return(_a0 *vcs.BlameResult, _a1 error) *MockRepository_Blame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Blame_Call) RunAndReturn(run func(vcs.Commit, string) (*vcs.BlameResult, error)) *MockRepository_Blame_Call {
	_c.Call.Return(run)
	return _c
}

// CommitObject provides a mock function with given fields: hash
func (_m *MockRepository) CommitObject(hash plumbing.Hash) (vcs.Commit, error) {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for CommitObject")
	}

	var r0 vcs.Commit
	var r1 error
	if rf, ok := ret.Get(0).(func(plumbing.Hash) (vcs.Commit, error)); ok {
		return rf(hash)
	}
	if rf, ok := ret.Get(0).(func(plumbing.Hash) vcs.Commit); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.Commit)
		}
	}

	if rf, ok := ret.Get(1).(func(plumbing.Hash) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CommitObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitObject'
type MockRepository_CommitObject_Call struct {
	*mock.Call
}

// CommitObject is a helper method to define mock.On call
//   - hash plumbing.Hash
func (_e *MockRepository_Expecter) CommitObject(hash interface{}) *MockRepository_CommitObject_Call {
	return &MockRepository_CommitObject_Call{Call: _e.mock.On("CommitObject", hash)}
}

func (_c *MockRepository_CommitObject_Call) Run(run func(hash plumbing.Hash)) *MockRepository_CommitObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(plumbing.Hash))
	})
	return _c
}

func (_c *MockRepository_CommitObject_Call) Return(_a0 vcs.Commit, _a1 error) *MockRepository_CommitObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CommitObject_Call) RunAndReturn(run func(plumbing.Hash) (vcs.Commit, error)) *MockRepository_CommitObject_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function with no fields
func (_m *MockRepository) Head() (vcs.Reference, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 vcs.Reference
	var r1 error
	if rf, ok := ret.Get(0).(func() (vcs.Reference, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() vcs.Reference); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.Reference)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockRepository_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Head() *MockRepository_Head_Call {
	return &MockRepository_Head_Call{Call: _e.mock.On("Head")}
}

func (_c *MockRepository_Head_Call) Run(run func()) *MockRepository_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Head_Call) Return(_a0 vcs.Reference, _a1 error) *MockRepository_Head_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Head_Call) RunAndReturn(run func() (vcs.Reference, error)) *MockRepository_Head_Call {
	_c.Call.Return(run)
	return _c
}

// Log provides a mock function with given fields: opts
func (_m *MockRepository) Log(opts *vcs.LogOptions) (vcs.CommitIterator, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 vcs.CommitIterator
	var r1 error
	if rf, ok := ret.Get(0).(func(*vcs.LogOptions) (vcs.CommitIterator, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*vcs.LogOptions) vcs.CommitIterator); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.CommitIterator)
		}
	}

	if rf, ok := ret.Get(1).(func(*vcs.LogOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockRepository_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - opts *vcs.LogOptions
func (_e *MockRepository_Expecter) Log(opts interface{}) *MockRepository_Log_Call {
	return &MockRepository_Log_Call{Call: _e.mock.On("Log", opts)}
}

func (_c *MockRepository_Log_Call) Run(run func(opts *vcs.LogOptions)) *MockRepository_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*vcs.LogOptions))
	})
	return _c
}

func (_c *MockRepository_Log_Call) Return(_a0 vcs.CommitIterator, _a1 error) *MockRepository_Log_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Log_Call) RunAndReturn(run func(*vcs.LogOptions) (vcs.CommitIterator, error)) *MockRepository_Log_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
