// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	vcs "github.com/panbanda/omen/internal/vcs"
	mock "github.com/stretchr/testify/mock"
)

// MockTree is an autogenerated mock type for the Tree type
type MockTree struct {
	mock.Mock
}

type MockTree_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTree) EXPECT() *MockTree_Expecter {
	return &MockTree_Expecter{mock: &_m.Mock}
}

// Diff provides a mock function with given fields: to
func (_m *MockTree) Diff(to vcs.Tree) (vcs.Changes, error) {
	ret := _m.Called(to)

	if len(ret) == 0 {
		panic("no return value specified for Diff")
	}

	var r0 vcs.Changes
	var r1 error
	if rf, ok := ret.Get(0).(func(vcs.Tree) (vcs.Changes, error)); ok {
		return rf(to)
	}
	if rf, ok := ret.Get(0).(func(vcs.Tree) vcs.Changes); ok {
		r0 = rf(to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vcs.Changes)
		}
	}

	if rf, ok := ret.Get(1).(func(vcs.Tree) error); ok {
		r1 = rf(to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTree_Diff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Diff'
type MockTree_Diff_Call struct {
	*mock.Call
}

// Diff is a helper method to define mock.On call
//   - to vcs.Tree
func (_e *MockTree_Expecter) Diff(to interface{}) *MockTree_Diff_Call {
	return &MockTree_Diff_Call{Call: _e.mock.On("Diff", to)}
}

func (_c *MockTree_Diff_Call) Run(run func(to vcs.Tree)) *MockTree_Diff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(vcs.Tree))
	})
	return _c
}

func (_c *MockTree_Diff_Call) Return(_a0 vcs.Changes, _a1 error) *MockTree_Diff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTree_Diff_Call) RunAndReturn(run func(vcs.Tree) (vcs.Changes, error)) *MockTree_Diff_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTree creates a new instance of MockTree. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTree(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTree {
	mock := &MockTree{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
