// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/panbanda/omen/internal/vcs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommitIterator creates a new instance of MockCommitIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommitIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommitIterator {
	mock := &MockCommitIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommitIterator is an autogenerated mock type for the CommitIterator type
type MockCommitIterator struct {
	mock.Mock
}

type MockCommitIterator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommitIterator) EXPECT() *MockCommitIterator_Expecter {
	return &MockCommitIterator_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockCommitIterator
func (_mock *MockCommitIterator) Close() {
	_mock.Called()
	return
}

// MockCommitIterator_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCommitIterator_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCommitIterator_Expecter) Close() *MockCommitIterator_Close_Call {
	return &MockCommitIterator_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCommitIterator_Close_Call) Run(run func()) *MockCommitIterator_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommitIterator_Close_Call) Return() *MockCommitIterator_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommitIterator_Close_Call) RunAndReturn(run func()) *MockCommitIterator_Close_Call {
	_c.Run(run)
	return _c
}

// ForEach provides a mock function for the type MockCommitIterator
func (_mock *MockCommitIterator) ForEach(fn func(vcs.Commit) error) error {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for ForEach")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(vcs.Commit) error) error); ok {
		r0 = returnFunc(fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommitIterator_ForEach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForEach'
type MockCommitIterator_ForEach_Call struct {
	*mock.Call
}

// ForEach is a helper method to define mock.On call
//   - fn func(vcs.Commit) error
func (_e *MockCommitIterator_Expecter) ForEach(fn interface{}) *MockCommitIterator_ForEach_Call {
	return &MockCommitIterator_ForEach_Call{Call: _e.mock.On("ForEach", fn)}
}

func (_c *MockCommitIterator_ForEach_Call) Run(run func(fn func(vcs.Commit) error)) *MockCommitIterator_ForEach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(vcs.Commit) error
		if args[0] != nil {
			arg0 = args[0].(func(vcs.Commit) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommitIterator_ForEach_Call) Return(err error) *MockCommitIterator_ForEach_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommitIterator_ForEach_Call) RunAndReturn(run func(fn func(vcs.Commit) error) error) *MockCommitIterator_ForEach_Call {
	_c.Call.Return(run)
	return _c
}
