// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	vcs "github.com/panbanda/omen/internal/vcs"
	mock "github.com/stretchr/testify/mock"
)

// MockFilePatch is an autogenerated mock type for the FilePatch type
type MockFilePatch struct {
	mock.Mock
}

type MockFilePatch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilePatch) EXPECT() *MockFilePatch_Expecter {
	return &MockFilePatch_Expecter{mock: &_m.Mock}
}

// Chunks provides a mock function with no fields
func (_m *MockFilePatch) Chunks() []vcs.Chunk {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Chunks")
	}

	var r0 []vcs.Chunk
	if rf, ok := ret.Get(0).(func() []vcs.Chunk); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vcs.Chunk)
		}
	}

	return r0
}

// MockFilePatch_Chunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chunks'
type MockFilePatch_Chunks_Call struct {
	*mock.Call
}

// Chunks is a helper method to define mock.On call
func (_e *MockFilePatch_Expecter) Chunks() *MockFilePatch_Chunks_Call {
	return &MockFilePatch_Chunks_Call{Call: _e.mock.On("Chunks")}
}

func (_c *MockFilePatch_Chunks_Call) Run(run func()) *MockFilePatch_Chunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFilePatch_Chunks_Call) Return(_a0 []vcs.Chunk) *MockFilePatch_Chunks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilePatch_Chunks_Call) RunAndReturn(run func() []vcs.Chunk) *MockFilePatch_Chunks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFilePatch creates a new instance of MockFilePatch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilePatch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilePatch {
	mock := &MockFilePatch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
