// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	vcs "github.com/panbanda/omen/internal/vcs"
	mock "github.com/stretchr/testify/mock"
)

// MockPatch is an autogenerated mock type for the Patch type
type MockPatch struct {
	mock.Mock
}

type MockPatch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPatch) EXPECT() *MockPatch_Expecter {
	return &MockPatch_Expecter{mock: &_m.Mock}
}

// FilePatches provides a mock function with no fields
func (_m *MockPatch) FilePatches() []vcs.FilePatch {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FilePatches")
	}

	var r0 []vcs.FilePatch
	if rf, ok := ret.Get(0).(func() []vcs.FilePatch); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vcs.FilePatch)
		}
	}

	return r0
}

// MockPatch_FilePatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilePatches'
type MockPatch_FilePatches_Call struct {
	*mock.Call
}

// FilePatches is a helper method to define mock.On call
func (_e *MockPatch_Expecter) FilePatches() *MockPatch_FilePatches_Call {
	return &MockPatch_FilePatches_Call{Call: _e.mock.On("FilePatches")}
}

func (_c *MockPatch_FilePatches_Call) Run(run func()) *MockPatch_FilePatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPatch_FilePatches_Call) Return(_a0 []vcs.FilePatch) *MockPatch_FilePatches_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPatch_FilePatches_Call) RunAndReturn(run func() []vcs.FilePatch) *MockPatch_FilePatches_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPatch creates a new instance of MockPatch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPatch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPatch {
	mock := &MockPatch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
